version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: FullStac/backend/Dockerfile
    restart: always
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://user:password@postgres:5432/dbname
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: FullStac/frontend/Dockerfile
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: